# Generated by Django 5.2 on 2025-08-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorlist',
            old_name='professor_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='studentlist',
            old_name='student_number',
            new_name='number',
        ),
    ]
