# Generated by Django 5.2 on 2025-08-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_professor_number_professorlist_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.IntegerField(blank=True, choices=[(0, 'industrial'), (1, 'computer'), (2, 'petroleum'), (3, 'chemical')], null=True, verbose_name='major'),
        ),
    ]
