# Generated by Django 5.2 on 2025-07-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(verbose_name='professor')),
                ('pronumber', models.IntegerField(verbose_name='professor number')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Saturday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start')),
                ('end_time', models.TimeField(verbose_name='start')),
                ('submitted_by', models.TextField(verbose_name='submitted by')),
            ],
        ),
        migrations.CreateModel(
            name='Conflicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_one', models.CharField(verbose_name='subject')),
                ('subject_two', models.CharField(verbose_name='subject')),
                ('submitted_by', models.TextField(verbose_name='submitted by')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Saturday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], verbose_name='day of week')),
                ('type', models.IntegerField(choices=[(0, 'exam'), (1, 'course')], verbose_name='type')),
                ('reporter', models.TextField(verbose_name='reporter')),
                ('solve', models.TextField(blank=True, null=True, verbose_name='solve')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='subject')),
                ('type', models.PositiveIntegerField(choices=[(0, 'general'), (1, 'required'), (2, 'core'), (3, 'practical'), (4, 'elective')], verbose_name='gender')),
                ('major', models.PositiveSmallIntegerField(choices=[(0, 'industrial'), (1, 'computer'), (2, 'petroleum'), (3, 'chemical')], verbose_name='major')),
                ('days', models.IntegerField(verbose_name='days')),
                ('length', models.FloatField(verbose_name='length')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='subject')),
                ('professor', models.CharField(verbose_name='professor')),
                ('major', models.PositiveSmallIntegerField(choices=[(0, 'industrial'), (1, 'computer'), (2, 'petroleum'), (3, 'chemical')], verbose_name='major')),
                ('entry', models.IntegerField(choices=[(0, 'ورودی اول '), (1, 'ورودی دوم'), (3, 'ورودی سوم'), (4, 'ورودی چهارم')], verbose_name='year')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TextField(verbose_name='time')),
                ('submitted_by', models.TextField(verbose_name='submitted by')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='subject')),
                ('professor', models.CharField(verbose_name='professor')),
                ('major', models.PositiveSmallIntegerField(choices=[(0, 'industrial'), (1, 'computer'), (2, 'petroleum'), (3, 'chemical')], verbose_name='major')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Saturday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], verbose_name='day of week')),
                ('entry', models.IntegerField(choices=[(0, 'ورودی اول '), (1, 'ورودی دوم'), (3, 'ورودی سوم'), (4, 'ورودی چهارم')], verbose_name='year')),
                ('start_time', models.TimeField(verbose_name='start')),
                ('end_time', models.TimeField(verbose_name='start')),
                ('submitted_by', models.TextField(verbose_name='submitted by')),
            ],
        ),
    ]
