# Generated by Django 5.2 on 2025-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflicts',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.FloatField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.FloatField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='conflicts',
            name='solve',
            field=models.IntegerField(blank=True, choices=[(0, 'در حال بررسی'), (1, 'بررسی شده')], default=0, null=True, verbose_name='solve'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'general'), (1, 'required'), (2, 'core'), (3, 'practical'), (4, 'elective')], verbose_name='type'),
        ),
    ]
