# Generated by Django 5.2 on 2025-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_remove_conflicts_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflicts',
            name='solve',
            field=models.CharField(blank=True, null=True, verbose_name='solve'),
        ),
    ]
